### ISSUE TITLE
使用waline时`hexo g`报错

### ISSUE THREAD

**Issue by symlPigeon** [zkz098/hexo-theme-shokaX#29]
### 问题发生位置

Hexo渲染报错

### 问题描述

设置waline之后`hexo g && hexo s`报错。

```
ERROR 
TypeError: /home/syml/Sources/blog-src/node_modules/hexo-theme-shokax/layout/_mixin/comment.pug:28
    26|                     init({
    27|                         el: '#wcomments',
  > 28|                         serverURL: '#{hexo.theme.config.waline.serverURL}',
    29|                         lang: '#{hexo.theme.config.waline.lang}',
    30|                         locale: !{locale},
    31|                         emoji: !{emoji},

Cannot read properties of undefined (reading 'theme')
    at Object.pug_interp [as CommentRender] (eval at wrap (/home/syml/Sources/blog-src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:183:62)
    at eval (eval at wrap (/home/syml/Sources/blog-src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:889:28)
    at template (eval at wrap (/home/syml/Sources/blog-src/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1114:7)
    at _View._compiled (/home/syml/Sources/blog-src/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/home/syml/Sources/blog-src/node_modules/hexo/lib/theme/view.js:39:17)
    at /home/syml/Sources/blog-src/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/home/syml/Sources/blog-src/node_modules/bluebird/js/release/util.js:16:23)
    at /home/syml/Sources/blog-src/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/syml/Sources/blog-src/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:987:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

感觉应该是`layout/_mixin/comment.pug`模板参数的问题，对应的几行改成这样子就能解决了：

```
//- Line 25 to 39
setTimeout(function () {
    init({
        el: '#wcomments',
        serverURL: '#{theme.waline.serverURL}', //-  hexo.config.theme -> theme，下同
        lang: '#{theme.waline.lang}',
        locale: !{locale},
        emoji: !{emoji},
        meta: !{meta},
        requiredMeta: !{requiredMeta},
        wordLimit: #{theme.waline.wordLimit},
        pageSize: #{theme.waline.pageSize},
        pageview: #{theme.waline.pageview},
        path: path
    });
}, 1000)
```

### 复现步骤

主题配置中设置waline：

```
# https://waline.js.org/
waline:
  enable: true
  serverURL: "https://*******"
  lang: "zh-CN"
  locale: {} # https://waline.js.org/guide/features/i18n.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80
  emoji: # 表情包
    - https://unpkg.com/@waline/emojis@1.0.1/weibo
    - https://unpkg.com/@waline/emojis@1.0.1/alus
    - https://unpkg.com/@waline/emojis@1.0.1/bilibili
    - https://unpkg.com/@waline/emojis@1.0.1/qq
    - https://unpkg.com/@waline/emojis@1.0.1/tieba
    - https://unpkg.com/@waline/emojis@1.0.1/tw-emoji
  meta: # 可以填写的内容
    - name
    - mail
    - link
  requiredMeta: # 必须填写的内容
    - name
    - mail
  wordLimit: 0 # 字数限制,0为不限制
  pageSize: 10 # 每页评论条数
  pageview: true # 是否开启浏览量统计
```

运行`hexo g`报错。

### 相关配置

```
$ node --version
v16.19.0
$ hexo --version
INFO  Validating config
hexo: 6.3.0
hexo-cli: 4.3.0
os: linux 6.1.8-arch1-1 Arch Linux
node: 16.19.0
v8: 9.4.146.26-node.24
uv: 1.43.0
zlib: 1.2.11
brotli: 1.0.9
ares: 1.18.1
modules: 93
nghttp2: 1.47.0
napi: 8
llhttp: 6.0.10
openssl: 1.1.1s+quic
cldr: 41.0
icu: 71.1
tz: 2022f
unicode: 14.0
ngtcp2: 0.8.1
nghttp3: 0.7.0
```

### 注意事项

- [X] 我已确认以上事项
