### ISSUE TITLE
lantern extention cannot be disabled

### ISSUE THREAD

**Issue by duchenpaul** [zkz098/hexo-theme-shokaX#32]
### 在开始之前......

- [X] 我理解 Issue 是用于反馈和解决问题的，将尽可能提供更多信息帮助问题解决
- [X] 我填写了简短且清晰明确的标题，以便开发者在收到 Issue 时能快速确定大致问题。而不是"一个问题"、"报错了"等
- [X] 我确认最新版尚未修复此问题，且此前没有人提出过此问题

### 问题发生位置

Hexo渲染报错

### 问题描述

Lantern cannot be disabled when the enable flag is set as `false`

```yaml
  lantern:
    enable: false #是否开启
    word1: 🤡 #第一个字
    word2: 💩 #第二个字
```

### 复现步骤

Set enable as `false`, redeploy

### 注意事项

- [X] 我已确认以上事项
